name: Tests via Docker Compose

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses:  actions/checkout@v4
      - run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
      - if: always()
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml down
